routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function(){

    // Projects

    Route::resource('projects', 'ProjectsController');

    Route::get('projects/destroy/{id}', [

        'uses'  => "ProjectsController@destroy",
        'as' => "projects.destroy"
    ]);

    // Users

    Route::resource('users', 'UsersController');

    Route::get('users/destroy/{user}', [

        "uses" => "UsersController@destroy",
        "as" => "users.destroy"
    ]);

    // Tareas

    Route::resource('tasks', 'TasksController');

    Route::get('tasks/destroy/{task}', [

        "uses" => "TasksController@destroy",
        "as" => "tasks.destroy"
    ]);

    // Comentarios

    Route::resource('comments', 'CommentsController');

    Route::get('comments/destroy/{comment}', [

        "uses" => "CommentsController@destroy",
        "as" => "comments.destroy"
    ]);

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $table = "users";

    protected $fillable = [
        'name', 'email', 'password', 'avatar', 'type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function projects(){

        return $this->hasMany('App\Project');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'ASC')->paginate(3);
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User($request->all());
        $user->password = bcrypt( $request->password );

        if( $user->save() ){

            flash('Usuario registrado exitosamente');
            return redirect()->route('users.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->avatar = $request->avatar;
        $user->type = $request->type;

        if( $user->save() ){

            flash("usuario modificado exitosamente")->success();
            return redirect()->route('users.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if( $user->delete() ){

            flash('El Usuario ' . $user->name . ' fue eliminado exitosamente')->warning();
            return redirect()->route('users.index');
        }
    }
}

resources/views/users/add.blade.php
@extends('template.master')

@section('title', 'Agregar usuario')

@section('content')
    <form class="form-horizontal" action="{{route('users.store')}}" method="post" required />
        <div class="form-group">
            <div class="col-xs-12">
                <label>Nombre</label>
                <input name="name" type="text" class="form-control" placeholder="Nombre" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Correo electrónico</label>
                <input name="email" type="email" class="form-control" placeholder="E-mail" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Contraseña</label>
                <input name="password" type="password" class="form-control" placeholder="Contraseña" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
            <label>Avatar</label>
                <input name="avatar" type="text" class="form-control" placeholder="Avatar" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Tipo</label>
                <select name="type" id="" class="form-control">
                    <option value="administrator">Administrador</option>
                    <option value="leader">Líder</option>
                    <option value="registered">Registrado</option>
                </select>
            </div>
        </div>       

        <div class="form-group">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Enviar">
            </div>
        </div>
        {{ csrf_field() }}
    </form>
@endsection

resources/views/users/edit.blade.php
@extends('template.master')

@section('title', 'Edición de usuario')

@section('content')
    <form class="form-horizontal" action="{{route('users.update', $user->id)}}" method="post">
        <div class="form-group">
            <div class="col-xs-12">
                <input type="hidden" name="_method" value="put" />
                <label>Nombre</label>
                <input name="name" type="text" class="form-control" placeholder="Nombre" value="{{$user->name}}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Correo Electrónico</label>
                <input name="email" type="email" class="form-control" placeholder="E-mail" value="{{$user->email}}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Avatar</label>
                <input name="avatar" type="text" class="form-control" placeholder="avatar" value="{{$user->avatar}}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Tipo</label>
                <select name="type" class="form-control" value="{{$user->type}}" required>
                    <option value="administrator">Administrador</option>
                    <option value="leader">líder</option>
                    <option value="registered">Registrado</option>
                </select>
            </div>
        </div>             

        <div class="form-group">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Enviar" />
            </div>
        </div>
        {{ csrf_field() }}
    </form>
@endsection

resources/views/users/index.blade.php
@extends('template.master')

@section('title', 'Lista de Usuarios')

@section('content')

    <table class="table table-striped">
        <thead>
            <th>Nombre</th>
            <th>Correo Electrónico</th>
            <th>Avatar</th>
            <th>Tipo</th>            
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->avatar}}</td>
                    <td>{{$user->type}}</td>                    
                    <td>
                        <button class="btn btn-danger">
                            <a href="{{route('users.destroy', $user->id)}}" onclick="confirm('¿Estas seguro que deseas eliminarlo?')">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </button>
                        <button class="btn btn-warning">
                            <a href="{{route('users.edit', $user->id)}}">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                        </button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table> 

    {!! $users->render() !!}

@endsection