routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function(){

    // Projects

    Route::resource('projects', 'ProjectsController');

    Route::get('projects/destroy/{id}', [

        'uses'  => "ProjectsController@destroy",
        'as' => "projects.destroy"
    ]);

    // Users

    Route::resource('users', 'UsersController');

    Route::get('users/destroy/{user}', [

        "uses" => "UsersController@destroy",
        "as" => "users.destroy"
    ]);

    // Tareas

    Route::resource('tasks', 'TasksController');

    Route::get('tasks/destroy/{task}', [

        "uses" => "TasksController@destroy",
        "as" => "tasks.destroy"
    ]);

    // Comentarios

    Route::resource('comments', 'CommentsController');

    Route::get('comments/destroy/{comment}', [

        "uses" => "CommentsController@destroy",
        "as" => "comments.destroy"
    ]);

});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{

    protected $table = "comments";

    protected $fillable = [
        'title', 'comment', 'tags', 'task_id', 'user_id'
    ];

    public function task(){

        return $this->belongsTo('App\Task');
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Comment;
use App\Task;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $comments = Comment::orderBy('id', 'DESC')->paginate(2);
        return view('comments.index')->with('comments', $comments);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tasks = Task::all();
        return view('comments.add')->with('tasks', $tasks);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $comment = new Comment( $request->all() );
        if( $comment->save() ){

            flash('El comentario fue agregado correctamente');
            return redirect()->route('comments.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment = Comment::find($id);

        return view('comments.edit')->with('comment', $comment);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);
        $comment->fill( $request->all() );

        if( $comment->save() ){

            flash('Comentario modificado exitosamente')->success();
            return redirect()->route('comments.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);

        if( $comment->delete() ){

            flash('Comentario eliminado satisfactoriamente');
            return redirect()->route('comments.index');
        }
    }
}

resources/views/comments/add.blade.php
@extends('template.master')

@section('title', 'Agregar comentario')

@section('content')
    <form class="form-horizontal" action="{{ route('comments.store') }}" method="post" required />
        <div class="form-group">
            <div class="col-xs-12">
                <label>Título</label>
                <input name="title" type="text" class="form-control" placeholder="Título" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Comentario</label>
                <input name="comment" type="text" class="form-control" placeholder="comentario" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Etiquetas (separadas por comas)</label>
                <input name="tags" type="text" class="form-control" placeholder="Tags" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Tarea</label>
                <select name="task_id" id="" class="form-control">
                    @foreach( $tasks as $task )
                        <option value="{{$task->id}}">{{$task->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-xs-12">
                <input name="user_id" type="hidden" value="1" class="form-control" placeholder="Fecha final">
            </div>
        </div>        

        <div class="form-group">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Enviar">
            </div>
        </div>
        {{ csrf_field() }}
    </form>
@endsection

resources/views/comments/edit.blade.php
@extends('template.master')

@section('title', 'Edición de comentario')

@section('content')
    <form class="form-horizontal" action="{{route('comments.update', $comment->id)}}" method="post">

        <div class="form-group">
            <div class="col-xs-12">
                <input type="hidden" name="_method" value="put" />
                <label>Título</label>                
                <input name="title" type="text" class="form-control" placeholder="Título" value="{{ $comment->title }}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Comentario</label>
                <input name="comment" type="text" class="form-control" placeholder="comentario" value="{{ $comment->comment }}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Etiquetas (separadas por comas)</label>
                <input name="tags" type="text" class="form-control" placeholder="Tags" value="{{ $comment->tags }}" required />
            </div>
        </div>       

        <div class="form-group">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Enviar" />
            </div>
        </div>
        {{ csrf_field() }}
    </form>
@endsection

resources/views/comments/index.blade.php
@extends('template.master')

@section('title', 'Lista de comentarios')

@section('content')

    <table class="table table-striped">
        <thead>
            <th>Titulo</th>
            <th>Comentario</th>
            <th>Etiquetas</th>    
            <th>Acciones</th>        
        </thead>    
        <tbody>
            @foreach($comments as $comment)
                <tr>
                    <td>{{$comment->title}}</td>
                    <td>{{$comment->comment}}</td>
                    <td>{{$comment->tags}}</td>                    
                    <td>
                        <button class="btn btn-danger">
                            <a href="{{route('comments.destroy', $comment->id)}}" onclick="confirm('¿Estas seguro que deseas eliminarlo?')">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </button>
                        <button class="btn btn-warning">
                            <a href="{{route('comments.edit', $comment->id)}}">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                        </button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table> 

    {!! $comments->render() !!}

@endsection