routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin'], function(){

    // Projects

    Route::resource('projects', 'ProjectsController');

    Route::get('projects/destroy/{id}', [

        'uses'  => "ProjectsController@destroy",
        'as' => "projects.destroy"
    ]);

    // Users

    Route::resource('users', 'UsersController');

    Route::get('users/destroy/{user}', [

        "uses" => "UsersController@destroy",
        "as" => "users.destroy"
    ]);

    // Tareas

    Route::resource('tasks', 'TasksController');

    Route::get('tasks/destroy/{task}', [

        "uses" => "TasksController@destroy",
        "as" => "tasks.destroy"
    ]);

    // Comentarios

    Route::resource('comments', 'CommentsController');

    Route::get('comments/destroy/{comment}', [

        "uses" => "CommentsController@destroy",
        "as" => "comments.destroy"
    ]);

});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $table = "tasks";

    protected $fillable = [
        'name', 'description', 'alias', 'status', 'initialDate', 'finalDate', 'spentTime', 'assigned_user', 'project_id'
    ];

    public function project(){

        return $this->belongsTo('App\Project');
    }

    public function comments(){

        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\Project;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::orderBy('id', 'DESC')->paginate('2');
        return view('tasks.index')->with('tasks', $tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $projects = Project::all();
        //dd($projects);
        return view('tasks.add')->with('projects', $projects);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $task = new Task( $request->all() );
        if( $task->save() ){

            flash('Tarea registrada exitosamente')->success();
            return redirect()->route('tasks.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        return view('tasks.edit')->with('task', $task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $task = Task::find($id);

        $task->fill( $request->all() );

        if( $task->save() ){

            flash('Tarea modificada con exito')->success();

            return redirect()->route('tasks.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        if( $task->delete() ){

            flash('Tarea eliminada satisfactoriamente')->warning();
            return redirect()->route('tasks.index');
        }
    }
}

resources/views/tasks/add.blade.php
@extends('template.master')

@section('title', 'Agregar Tarea')

@section('content')
    <form class="form-horizontal" action="{{ route('tasks.store') }}" method="post" required />
        <div class="form-group">
            <div class="col-xs-12">
                <label>Nombre</label>
                <input name="name" type="text" class="form-control" placeholder="Nombre" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Descripción</label>
                <input name="description" type="text" class="form-control" placeholder="descripción" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Alias</label>
                <input name="alias" type="text" class="form-control" placeholder="avatar" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Proyecto</label>
                <select name="project_id" class="form-control">
                    @foreach( $projects as $project )
                        <option value="{{$project->id}}"> {{$project->name}} </option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Fecha inicial</label>
                <input name="initialDate" type="text" class="date form-control" placeholder="Fecha Inicial" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Fecha final</label>
                <input name="finalDate" type="text" class="date form-control" placeholder="Fecha final" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Tiempo empleado</label>
                <input name="spentTime" type="text" class="form-control" placeholder="Tiempo empleado" required />
            </div>
        </div>       

        <div class="form-group">
            <div class="col-xs-12">
                <input name="assigned_user" type="hidden" value="1" class="form-control" placeholder="Fecha final" required>
            </div>
        </div>        

        <div class="form-group">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Enviar">
            </div>
        </div>
        {{ csrf_field() }}
    </form>
@endsection

resources/views/tasks/edit.blade.php
@extends('template.master')

@section('title', 'Edición de Tarea')

@section('content')
    <form class="form-horizontal" action="{{route('tasks.update', $task->id)}}" method="post">
        <div class="form-group">
            <div class="col-xs-12">                
                <input type="hidden" name="_method" value="put" />
                <labelNombre></label>
                <input name="name" type="text" class="form-control" placeholder="Nombre" value="{{$task->name}}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Descripción</label>
                <input name="description" type="text" class="form-control" placeholder="descripción" value="{{$task->description}}" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <label>Alias</label>
                <input name="alias" type="text" class="form-control" placeholder="Alias" value="{{$task->alias}}" required />
            </div>
        </div>        
        <div class="form-group">
            <div class="col-xs-12">
                <label>Fecha inicial</label>
                <input name="initialDate" type="text" class="date form-control" placeholder="Fecha Inicial" value="{{$task->initialDate}}" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <label>Fecha final</label>
                <input name="finalDate" type="text" class="date form-control" placeholder="Fecha final" value="{{$task->finalDate}}" required />
            </div>
        </div> <div class="form-group">
            <div class="col-xs-12">
                <label>Tiempo Empleado</label>
                <input name="spentTime" type="text" class="form-control" placeholder="Tiempo empleado" value="{{$task->spentTime}}" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <input class="btn btn-primary" type="submit" value="Enviar" />
            </div>
        </div>
        {{ csrf_field() }}
    </form>
@endsection

resources/views/tasks/index.blade.php
@extends('template.master')

@section('title', 'Lista de Tareas')

@section('content')

    <table class="table table-striped">
        <thead>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Alias</th>
            <th>Estado</th>            
            <th>Fecha Inicial</th>
            <th>Fecha final</th>
            <th>Tiempo empleado</th>
            <th>Acciones</th>
        </thead>    
        <tbody>
            @foreach($tasks as $task)
                <tr>
                    <td>{{$task->name}}</td>
                    <td>{{$task->description}}</td>
                    <td>{{$task->alias}}</td>                    
                    <td>{{$task->status}}</td>
                    <td>{{$task->initialDate}}</td>
                    <td>{{$task->finalDate}}</td>
                    <td>{{$task->spentTime}}</td>
                    <td>
                        <button class="btn btn-danger">
                            <a href="{{route('tasks.destroy', $task->id)}}" onclick="confirm('¿Estas seguro que deseas eliminarlo?')">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </button>
                        <button class="btn btn-warning">
                            <a href="{{route('tasks.edit', $task->id)}}">
                                <i class="glyphicon glyphicon-pencil"></i>
                            </a>
                        </button>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table> 

    {!! $tasks->render() !!}

@endsection